 
language: android
jdk: oraclejdk8

sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
    - /usr/local/android-sdk-25.2.3
android:
  components:
    - tools
    - platform-tools
before_script:

  - echo "y" | sdkmanager "emulator" "extras;google;google_play_services" "extras;google;m2repository" "extras;android;m2repository" "build-tools;27.0.3" "platform-tools" "platforms;android-24" "platforms;android-27" "system-images;android-24;default;armeabi-v7a"
  - echo "y" | sdkmanager --update

  - ./gradlew androidDependencies

  - echo "no" | android create avd --force -n test -k "system-images;android-24;default;armeabi-v7a"

  - export QEMU_AUDIO_DRV=none
  - export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
  - $ANDROID_HOME/emulator/emulator -avd test -noaudio -accel on -use-system-libs -verbose &

  - android-wait-for-emulator

  - echo ${ANDROID_HOME}

  - while [ "`adb shell getprop sys.boot_completed | tr -d '\r' `" != "1" ] ; do sleep 1; done

script:
  - "travis_wait 30 sleep 1800 &"
  - ./gradlew clean lint test check connectedCheck --info --stacktrace
