 
language: android
jdk: oraclejdk8

sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/
android:
  components:
    - tools
    - platform-tools
before_script:
  - export JVM_OPTS="-Xmx3200m"
  - echo "y" | sdkmanager "emulator" "extras;google;google_play_services" "extras;google;m2repository" "extras;android;m2repository" "build-tools;27.0.3" "platform-tools" "platforms;android-24" "platforms;android-27" "system-images;android-24;default;armeabi-v7a"
  - echo "y" | sdkmanager --update

  - ./gradlew androidDependencies

  - echo "no" | android create avd --force -n test24 -k "system-images;android-24;default;armeabi-v7a"

  - export QEMU_AUDIO_DRV=none
  - export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
  - $ANDROID_HOME/emulator/emulator -avd test24 -noaudio -no-boot-anim -no-window -accel on -use-system-libs -verbose &

  - android-wait-for-emulator



script:
  - "travis_wait 30 sleep 1800 &"
  - echo "start waiting"
  - while [ "`adb shell getprop sys.boot_completed | tr -d '\r' `" != "1" ] ; do sleep 1; done
  - adb shell getprop
  - ./gradlew clean lint test check connectedCheck connectedAndroidTest --info --stacktrace
