version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Update android sdk
          command: |
              echo "y" | sdkmanager "tools" "emulator" "lldb;3.1" "extras;google;google_play_services" "extras;google;m2repository" "extras;android;m2repository" "build-tools;19.1.0" "build-tools;27.0.3" "platform-tools" "platforms;android-19" "platforms;android-27" "system-images;android-19;google_apis;armeabi-v7a"
              echo "y" | sdkmanager --update
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Setup emulator
          command: echo "no" | avdmanager create avd -n test -k "system-images;android-19;google_apis;armeabi-v7a"
      - run:
          name: Launch emulator
          command: |
              export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
              emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on -use-system-libs -verbose
          background: true

      - run:
          name: Wait emulator
          command: |
              circle-android wait-for-boot
              adb shell input keyevent 82
      - run:
          name: Run Tests
          command: ./gradlew clean lint test check connectedCheck connectedAndroidTest  --info --stacktrace
      - run:
          name: Run Upload
          command: java -jar lib/codacy-coverage-reporter-4.0.1-assembly.jar report -l Java -r app/build/reports/coverage/debug/report.xml -t ${CodacyToken} --commit-uuid ${CIRCLE_SHA1}

      - run:
          name: Deploy Over GIT
          command: |
            ./gradlew assemble
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            export TERM=linux
            export TERMINFO=/etc/terminfo
            sudo apt-get update && sudo apt-get install yarn
            yarn add publish-release
            cp app/build/outputs/apk/release/app-release-unsigned.apk install/ -f
            cp app/build/outputs/apk/debug/app-debug.apk install/ -f
            last=$(git describe --abbrev=0 --tags)
            echo $last
            last="${last:1}"
            echo $last
            newTag=$(($last + 1))
            echo $newTag
            newTag="v${newTag}"
            echo $newTag
            git tag "$newTag"
            git push origin "$newTag"
            yarn run publish-release --reuseRelease --assets install/app-debug.apk,install/app-release-unsigned.apk --owner "VSSSE" --repo "VSS-Mobile" --tag "$newTag" --name "Movie Tunes 1.0.0" --notes "This is a developer release! Use it on your own risk" --token ${GIT_TOKEN} >> yarn.log
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/outputs/androidTest-results/connected
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples


