version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      QEMU_AUDIO_DRV: none
    pre:
      - emulator -avd circleci-android27 -no-window:
         background: true
         parallel: true
      - circle-android wait-for-boot
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "myapplication/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "myapplication/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew clean check connectedCheck
      - store_artifacts:
          path: myapplication/build/reports
          destination: reports
      - store_test_results:
          path: myapplication/build/outputs/androidTest-results/connected
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples    
