 test:
  pre:
    - emulator -avd circleci-android27 -no-audio -no-window:
        background: true
        parallel: true
    - circle-android wait-for-boot
  override:
- ./gradlew testDebug connectedAndroidTest
